# Generated by Django 5.0.2 on 2024-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("amazon", "Amazon"),
                            ("groceries", "Groceries"),
                            ("eating_out", "Eating Out"),
                            ("school", "School"),
                            ("car", "Car"),
                            ("auto_insurance", "Auto Insurance"),
                            ("gas", "Gas"),
                            ("mortgage", "Mortgage"),
                            ("hoa", "HOA"),
                            ("utilities", "Utilities"),
                            ("house", "House"),
                            ("internet", "Internet"),
                            ("phone", "Phone"),
                            ("gym", "Gym"),
                            ("gifts", "Gifts"),
                            ("medical_health", "Medical / Health"),
                            ("needs", "Needs"),
                            ("wants", "Wants"),
                            ("gross_income", "Gross Income"),
                            ("net_income", "Net Income"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
